data:
  raw_data_path: '/Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Matching_string_project/Data/train.csv'
  processed_data_path: '/Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Matching_string_project/Data/cleaned.csv'
  target_col: 'is_duplicate'
  index_col: 'pair_id'
  text_col: 'name_1'

train:
  RAND: 10
  test_size: 0.2
  batch_size: 16
  model_name: 'distilbert-base-nli-mean-tokens'
  model_path: '/Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Matching_string_project/Models/sent_bert.joblib'
  n_epoch: 1
  embeddings_path: '/Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Matching_string_project/Data/embedding.csv'
