data:
  raw_data_path: '/data/processed/train.csv'
  processed_data_path: '/data/processed/cleaned.csv'
  target_col: 'is_duplicate'
  index_col: 'pair_id'
  text_col: 'name_1'

train:
  RAND: 10
  test_size: 0.2
  batch_size: 16
  model_name: 'distilbert-base-nli-mean-tokens'
  model_path: '/weights/sent_bert.joblib'
  n_epoch: 1
  embeddings_path: '/data/processed/embedding.csv'
